### ISSUE TITLE
Would love to see a Loom or asciicinema, etc for your setup and all of its features

### ISSUE THREAD

**Issue by megalithic** [fsouza/dotfiles#587]
This is just a random question; you have such an insane config; wildly complex and tailor-made to you and your needs; I'd love to see this in action. Ever thought about publishing recordings/live streams of your setup in use?

**Comment by fsouza** [comment]
Hi @megalithic, thanks for opening this issue. I am actually planning to start blogging again this year, so this is probably a good idea to cover in a series of blog posts including videos and demos.

**Comment by megalithic** [comment]
Thanks for the response @fsouza !! Looking forward to it.
